### ISSUE TITLE
Referesh buttons and Connection edit button

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#8]
The connection edit button should be moved from top left of the chart the the be right after the table name with a space because it more natural to want to click it there.
We have two refresh buttons: one on the Data Sources and one on Dimensions. We need only one and we should it to the top left of the chart where the Connection Edit button is now, which should be moved as per above.

**Comment by prahladyeri** [comment]
Fixed this in last commit. Feel free to test and reopen this issue.

**Comment by key2market** [comment]
Along with the connection button, moving it to the top left box would make sense as this is where the connections are located, but we also need to put the SQL option inside the popup to choose the table. Here is the screenshot of Tableau that I used from the video I uploaded.
As you can see, the New Custom SQL option is right there next to all the tables. Could we have our button there as well? And if I choose custom SQL then default name should be Custom SQL and possibly let the user change it as well.

![screen shot 2016-01-04 at 9 38 53 am](https://cloud.githubusercontent.com/assets/16460237/12086127/6207ce20-b2c7-11e5-9911-cd5edd824eea.png)


Kirill

**Comment by prahladyeri** [comment]
Sure, will do it.

**Comment by prahladyeri** [comment]
Fixed. Feel free to test and reopen. One thing to note about `CustomSQL`:

With CustomSQL its difficult to segregate the measures/dimensions from the returned columns, because it is `one whole query` rather than building a query by picking the columns and tables and building the `sql` as we usually do. For example, I used the following custom SQL:

    SELECT * FROM playground.Orders;

The app determined from output that `OrderID` and `ProductID` are measures, rest are dimensions. But when you drag them to rows/columns and the app goes to build the sql in order to draw the chart, it cannot perform complex regex string analysis on the SQL statement `SELECT * FROM playground.Orders;` (though programs like `tableau` might be doing such a thing as they are full desktop apps). Instead, what I did was, just put your whole CustomSQL as a subquery alias, so your measure/dimension in this example will be queried as follows:

    SELECT COUNT(OrderID),CustFirstName FROM (SELECT * FROM playground.Orders) alias GROUP BY CustFirstName

Please note that this may or may not work with `PostgreSQL`. I don't have pgsql, but let me know whenever you want this tested with pgsql and I'll do it.

**Comment by key2market** [comment]
THis is perfect!

**Comment by key2market** [comment]
HI Prahlad, I would have to reopen this one. I requested the bellow earlier:
Along with the connection button, moving it to the top left box would make sense as this is where the connections are located, but we also need to put the SQL option inside the popup to choose the table. Here is the screenshot of Tableau that I used from the video I uploaded.

**Comment by key2market** [comment]
I can see that you have added the custom SQL. We just need to remove the SQL from the top right of the chart to avoid the confusion because SQL button there shows something completely different. 
And Edit Connection should be moved from top right of the chart to the data source in the Data Sources on the top left of page. Each data source would have the edit button after it.
The two refresh buttons that are on Data Sources and Dimensions - why are they there? Should we remove them both and add one on the top right of the chart to refresh the chart after we finish building the Vizualization? sort of like On/Off for autorefresh?

**Comment by prahladyeri** [comment]
Fixed. Feel free to test and reopen. Regarding:

> The two refresh buttons that are on Data Sources and Dimensions - why are they there?

Design mistake, I've removed them now. My original idea was to display an `animation` by rotating the refresh icon whilst the mysql connection was being done in the background. But then I realized that slow internet connections are only a problem in India :smile:. In your Europe and Americas, it will connect in the blink of an eye and you will not even notice that refresh icon rotating. So, its redundant.
